# Permalinks
permalink:           pretty

# Setup
title:               Kyma
tagline:             'Sensores, Control e IA'
description:         'Grupo de investigaci칩n centrado en el dise침o e implementaci칩n de sens칩rica, control e Inteligencia artificial'
baseurl:             ''
# baseurl:             ''

# About/contact
author:
  name:              Kyma Team
  url:               http://github.com/kyma-un

# Custom vars
version:             1.1.2

sass:
  load_paths:
    - styles/scss
  style: compressed