# Permalinks
permalink:           pretty

# Setup
title:               Battery Intelligence Lab
tagline:             'Energy storage systems'
description:         'A research group focused on system design, monitoring and control of electrochemical energy storage systems in applications from electric cars to grid power systems.'
baseurl:             ''
# baseurl:             ''

# About/contact
author:
  name:              Dan Lovell
  url:               http://danlovell.com

# Custom vars
version:             1.1.2
